# Generated by Django 6.1.1 on 2026-09-07 17:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=2000)),
                ('method', models.CharField(max_length=10)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=30, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=30, null=True)),
                ('address_country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code (e.g. CA)', max_length=2, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('address_postal_code', models.CharField(blank=True, max_length=11, null=True)),
                ('address_city', models.CharField(blank=True, max_length=60, null=True)),
                ('address_state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_cc', models.TextField(blank=True, help_text='Comma-separated list of CC emails')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_date', models.DateField()),
                ('address_tipo_logradouro', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=30, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=30, null=True)),
                ('address_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('address_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('address_city', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_document_number', models.IntegerField(default=1, help_text='Next RPS/DPS number to be used for new invoices')),
                ('nfse_provider', models.CharField(choices=[('PAULISTANA', 'Paulistana'), ('NACIONAL', 'Sefin Nacional')], default='PAULISTANA', max_length=20)),
                ('document_series', models.CharField(default='1', help_text='Série numérica do RPS/DPS (1 a 5 dígitos)', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,5}$', 'A série deve conter apenas dígitos numéricos (1 a 5 dígitos).')])),
                ('address_city_ibge', models.CharField(default='3550308', help_text='Código IBGE do município emissor (ex: 3550308 para São Paulo)', max_length=7)),
                ('default_codigo_tributacao_nacional', models.CharField(default='010101', help_text='Código de tributação nacional do ISSQN (LC 116)', max_length=6)),
                ('default_codigo_nbs', models.CharField(blank=True, help_text='Código NBS correspondente ao serviço', max_length=9, null=True)),
                ('bank_details_raw', models.TextField(blank=True, null=True)),
                ('debug_email', models.EmailField(blank=True, help_text='If set, all emails are redirected here for debugging.', max_length=254, null=True)),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug mode (routes emails to debug email and uses test NFS-e API)')),
                ('auto_finalize_invoices', models.BooleanField(default=False, help_text='Automatically finalize DRAFT invoices on their issue date.')),
                ('auto_send_emails', models.BooleanField(default=False, help_text='Automatically send emails after finalizing an invoice.')),
                ('auto_invoice_hour', models.IntegerField(default=9, help_text='Hour of the day (0-23) to run the automatic invoice finalization.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('CLIENT_INVOICE_ISSUED', 'Client: Invoice Issued'), ('COMPANY_INVOICE_ISSUED', 'Company: Invoice Issued'), ('COMPANY_CANCEL_FAILED', 'Company: Cancel Failed'), ('COMPANY_FAILSAFE_TRIGGERED', 'Company: Failsafe Triggered'), ('COMPANY_NFSE_ISSUED', 'Company: NFS-e Issued'), ('COMPANY_NFSE_FAILED', 'Company: NFS-e Failed')], help_text='Internal identifier for the email type', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese (Brazil)')], default='en', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {{ macros }} like {{ invoice_date }}, {{ prev_month_start }}, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the month', unique=True)),
                ('status', models.CharField(choices=[('CONSOLIDATED', 'Consolidado'), ('OUTDATED', 'Desatualizado - Requer Recálculo')], default='OUTDATED', max_length=20)),
                ('total_revenue_internal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_revenue_export', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('rbt12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fator_r_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('fator_r_payroll_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fator_r_cpp_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('actual_pro_labore_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('applied_annex', models.CharField(blank=True, choices=[('ANNEX_III', 'Anexo III (Fator R >= 28%)'), ('ANNEX_V', 'Anexo V (Fator R < 28%)')], max_length=20, null=True)),
                ('inss_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('irrf_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('das_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('das_cpp_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'ordering': ['-month_year'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('exchange_rate_to_brl', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PROCESSING', 'Processando'), ('FINALIZED', 'Finalizado'), ('CANCELED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='ID of the celery task currently processing this invoice.', max_length=255, null=True)),
                ('task_retry_count', models.IntegerField(default=0, help_text='Number of times the current task has been retried.')),
                ('document_number', models.IntegerField(blank=True, help_text='RPS/DPS Number', null=True)),
                ('document_series', models.CharField(blank=True, default='1', help_text='Série numérica do RPS/DPS (1 a 5 dígitos)', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$', 'A série deve conter apenas dígitos numéricos (1 a 5 dígitos).')])),
                ('protocolo_envio', models.CharField(blank=True, help_text='Protocol returned when batch is sent to prefeitura', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_foreign', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Can contain macros like {{ prev_month_start }}')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_foreign', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoicetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nf_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(db_index=True)),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_export', models.BooleanField(default=True, help_text='Exempts PIS, COFINS, ISS from DAS')),
                ('description', models.TextField()),
                ('verification_code', models.CharField(blank=True, help_text='Código de Verificação retornado pela prefeitura', max_length=100, null=True)),
                ('chave_acesso_nacional', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('codigo_tributacao_nacional', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_servico_municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_nbs', models.CharField(blank=True, max_length=20, null=True)),
                ('aliquota_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('xml_autorizacao', models.FileField(blank=True, null=True, upload_to='nfs_e/xmls/')),
                ('danfse_pdf', models.FileField(blank=True, null=True, upload_to='nfs_e/pdfs/')),
                ('is_canceled', models.BooleanField(default=False, help_text='Indicates if the NFS-e has been canceled.')),
                ('cancelation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_fiscal', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='NfseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_enviado', models.TextField(blank=True, null=True)),
                ('payload_retorno', models.TextField(blank=True, null=True)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, help_text='Origin (User/IP)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfse_logs', to='core.invoice')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfse_logs', to='core.notafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('INSS', 'INSS'), ('IRRF', 'IRRF'), ('ANNEX_III', 'Simples Nacional - Annex III'), ('ANNEX_V', 'Simples Nacional - Annex V')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tax_type', 'valid_from', 'valid_to'], name='core_taxtab_tax_typ_bdff16_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nominal_rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 15.5 for 15.5%)', max_digits=5)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cpp_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pis_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cofins_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('iss_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='core.taxtable')),
            ],
            options={
                'ordering': ['min_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('document_number', 'document_series'), name='unique_document'),
        ),
    ]
